### PR TITLE
start of about ola

### PR DESCRIPTION
**Pull request by paul-hammant**

### CODE REVIEW

**Comment by paul-hammant** [comment]
Folks?

**Comment by claucece** [comment]
Mmmm.. this is a nice idea.. @dmytri ?

**Comment by paul-hammant** [comment]
I can nudge 50 people that have worked with him in the past to say nice things. I socialized with Ola too in the San Francisco days, but not as much as others.

**Comment by paul-hammant** [comment]
Folks?

**Comment by claucece** [comment]
Thanks @paul-hammant . Here is also a list of Ola's projects (I put there your text): https://dfri.se/wiki/freeolabini/ola-sw-contributions.txt

**Comment by paul-hammant** [comment]
That's great. I think we can work in some commercial achievements too. e.g. "Architected the foobar doohickey that for a national space agency" and alike.

Are we going to keep such things in the https://dfri.se/wiki/freeolabini/ola-sw-contributions.txt wiki, or consume them into a timeline in this repo?  I mean, consume this PR?  It's in limbo and should be consumed or rejected with reason. What say you @dmytri

**Comment by dmytri** [comment]
added the new about-ola section and will merge this now

**Comment by claucece** [comment]
@paul-hammant @dmytri I will add the dfri text as well.

**Pull request merged**
